/* ═══════════════════════════════════════════════════════
     bridge.js — Phase 2: User Verification & Claiming
     Upgraded for Admin-Generation Flow + Base Mainnet
     Depends on: modal.js, app.js, export.js
═══════════════════════════════════════════════════════ */

/* ── CONFIG ─────────────────────────────────────────── */
const BRIDGE_CONFIG = {
  contractAddress: '0x8453...', // Replace with your Base contract
  mintPriceEth: '0.05',
  chainId: 8453, 
  chainName: 'Base',
  rpcUrl: 'https://mainnet.base.org',
  openSeaBase: 'https://opensea.io/collection/mech-rangers-official', 
  // Pointing to the snapshot generated by the Admin Forge
  snapshotUrl: './mint-snapshot.json', 
};

/* ── STATE ──────────────────────────────────────────── */
let _userWallet = null;
let _assignedNFT = null;
let _snapshot = null;

/* ── INIT ───────────────────────────────────────────── */
async function bridgeInit() {
  try {
    // Dynamically load the data you forged in the Admin panel
    const res = await fetch(BRIDGE_CONFIG.snapshotUrl);
    if (!res.ok) throw new Error("Snapshot not found");
    _snapshot = await res.json();
    console.log("Survivor Snapshot Loaded. Total Units:", _snapshot.generatedCount);
  } catch (err) {
    bridgeShowStatus('error', '⛔ No snapshot found. Admin must forge collection first.');
    console.error(err);
    return;
  }
  renderBridgeUI();
}

/* ── VERIFY ADDRESS (THE SEARCH) ────────────────────── */
async function bridgeVerifyAddress() {
  const input = document.getElementById('bridgeWalletInput');
  const address = input?.value.trim().toLowerCase();

  if (!address || !address.startsWith('0x')) {
    bridgeShowStatus('warn', 'Enter a valid 0x wallet address.');
    return;
  }

  _userWallet = address;
  
  // Cross-reference the search with your Admin-generated data
  // Logic: Checking the "rangers" array in your snapshot
  const assignment = _snapshot.rangers.find(r => r.holder === _userWallet);

  if (assignment) {
    // Find the full NFT details from allNFTs (populated by app.js/generator.js)
    _assignedNFT = allNFTs.find(n => n.id === assignment.id);
    renderWalletStatus(assignment);
    toast("Assignment Verified!", "success");
  } else {
    renderWalletStatus(null);
  }
}

/* ── CONNECT WALLET ─────────────────────────────────── */
async function bridgeConnect() {
  if (typeof window.ethereum === 'undefined') {
    bridgeShowStatus('warn', '🦊 Wallet not detected.');
    return;
  }
  try {
    const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
    document.getElementById('bridgeWalletInput').value = accounts[0];
    bridgeVerifyAddress();
  } catch (err) {
    bridgeShowStatus('error', `Connection failed: ${err.message}`);
  }
}

/* ── RENDER WALLET STATUS ────────────────────────────── */
async function renderWalletStatus(assignment) {
  const panel = document.getElementById('bridgeWalletPanel');
  if (!panel) return;

  if (!assignment) {
    panel.innerHTML = `
      <div class="bridge-status not-listed">
        <div class="bridge-title" style="color:var(--red)">NOT IN SNAPSHOT</div>
        <div class="bridge-msg">Address <code>${_userWallet.slice(0,8)}...</code> is not assigned a Ranger.</div>
        <button class="btn btn-outline" onclick="renderBridgeUI()" style="margin-top:10px">← TRY ANOTHER</button>
      </div>`;
    return;
  }

  const tierColors = { 
    legendary: '#ffc400', epic: '#b44fff', rare: '#00e5ff', 
    uncommon: '#00e676', common: '#6a6a9a' 
  };
  const tierColor = tierColors[assignment.tier] || '#fff';

  panel.innerHTML = `
    <div class="bridge-status whitelisted">
      <div class="bridge-tier" style="color:${tierColor}">★ ${assignment.tier.toUpperCase()} ASSIGNED</div>
      <div class="bridge-msg">Ranger Unit #${assignment.id} is reserved for you.</div>
      
      <div class="bridge-mint-row" style="margin-top:20px">
        <button class="btn btn-gen" style="width:100%" onclick="viewMyRanger(${assignment.id})">
          VIEW MY RANGER
        </button>
      </div>

      <div class="bridge-trust-box" style="margin-top:15px; border: 1px solid ${tierColor}44; padding: 10px; font-size: 0.75rem;">
        <p>Deployment: <strong>Base Mainnet</strong><br>Status: <strong>Ready to Claim</strong></p>
      </div>

      <button class="btn btn-outline" onclick="renderBridgeUI()" style="margin-top:15px; width:100%; border-color:transparent; font-size:0.7rem">CHANGE WALLET</button>
    </div>`;
}

/* ── VIEW ASSIGNED RANGER ───────────────────────────── */
function viewMyRanger(id) {
  // Pull the full NFT object from the global state
  const nft = allNFTs.find(n => n.id === id);
  if (nft) {
    openModal(nft); // Triggers the modal.js logic to show the visual
  } else {
    toast("Ranger data not loaded. Please wait...", "warn");
  }
}

/* ── STATUS MESSAGE ─────────────────────────────────── */
function bridgeShowStatus(type, msg) {
  const el = document.getElementById('bridgeStatus');
  if (!el) return;
  const colors = { success: '#00e676', warn: '#ffc400', error: '#ff1744', info: '#00e5ff' };
  el.style.color = colors[type] || '#fff';
  el.style.display = 'block';
  el.textContent = msg;
}

/* ── RENDER BRIDGE UI ───────────────────────────────── */
function renderBridgeUI() {
  const root = document.getElementById('bridgeRoot');
  if (!root) return;
  root.innerHTML = `
    <div class="bridge-panel">
      <div class="bridge-header">
        <div class="bridge-phase">BASE MAINNET — VERIFICATION</div>
        <div class="bridge-title-main">CHECK YOUR<br><span style="color:var(--cyan)">RANGER ASSIGNMENT</span></div>
      </div>
      <div id="bridgeStatus" style="display:none;padding:12px 0;font-family:'Share Tech Mono',monospace;font-size:.8rem"></div>
      
      <div id="bridgeWalletPanel">
        <div class="search-box">
          <input type="text" id="bridgeWalletInput" class="field-in" placeholder="Enter Wallet Address (0x...)" style="width:100%; margin-bottom:10px; text-align:center">
          <button class="btn btn-gen" style="width:100%;" onclick="bridgeVerifyAddress()">
            SEARCH BASE SNAPSHOT
          </button>
        </div>
        
        <div class="divider" style="margin:20px 0; text-align:center; color:var(--muted2); font-size:0.7rem">OR</div>
        
        <button class="btn btn-outline" style="width:100%; font-size:0.9rem; border-style:dashed" onclick="bridgeConnect()">
          🦊 CONNECT WITH METAMASK
        </button>
      </div>
    </div>`;
}

// Ensure the bridge initializes on load
window.addEventListener('DOMContentLoaded', bridgeInit);
